# Generated by Django 4.1.1 on 2022-09-05 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='comoleted',
            new_name='completed',
        ),
    ]
